#!/bin/bash

if [ $# != 3 ]; then
    echo "Usage: $0 es_host full_text_cache_deletion_name full_text_cache_html_deletion_name"
    echo "Use ID files generated by \"generate_all_es_duplicate_deletions_lists.sh\""
    exit 1
fi

es_host="$1"
shift

declare -a indices=("full_text_cache" "full_text_cache_html")
declare -a deletion_files=($1 $2)


declare -A indices_and_deletion_files

while read -r key value; do
   indices_and_deletion_files["$key"]="$value"
done < <(paste -d' ' <(printf '%s\n' ${indices[@]}) <(printf '%s\n' ${deletion_files[@]}))

for key in ${!indices_and_deletion_files[@]}; do
    cat  ${indices_and_deletion_files["$key"]} | xargs -I'{}' bash -c 'echo '"'"'{"delete" : { "_index" : '"'"'\"$1\"'"'"', "_id" : '"'"'\"$2\"'"'"'} }'"'"'' _ $key '{}' | \
    xargs -d '\n' -n 1000 bash -c \
    'curl --trace /tmp/trace.log -X POST "http://localhost:9200/_bulk" \
     -H "Content-Type: application/x-ndjson" --data-binary @<(echo $@ | sed -re '"'"'s/\{"delete/\n&/g'"'"' | sed -re '"'"'/^$/d'"'"')'
done
