# Based on code generated by AI
import configparser
import jq
import json
import random
from pydantic import BaseModel, Field, PrivateAttr, validator
from langchain_core.retrievers import BaseRetriever
from langchain_core.documents import Document
from pysolr import Solr
from typing import List,Dict,Optional,Any

class SolrConfig(BaseModel):
      host: str = "localhost"
      port: int = Field(default=8983, gt=0, le=65535)
      collection:  Optional[str] = Field(default="biblio")
      max_records: int = Field(default=200)
      batch_size: int = Field(default=100)
      keep_ratio: float = Field(default=1.0, gt=0.0, le=1.0)
      skip_pages: int = Field(default=0)

      @classmethod
      def load_config(cls, config_file: str):
          config = configparser.ConfigParser()
          config.read(config_file)
          if not config.has_section('Solr'):
              raise configparser.NoSectionError('Solr')

          solr_data = dict(config['Solr'])

          if 'port' in solr_data:
              solr_data['port'] = int(solr_data['port'])

          if 'max_records' in solr_data:
              solr_data['max_records'] = int(solr_data['max_records'])

          if 'batch_size' in solr_data:
              solr_data['batch_size'] = int(solr_data['batch_size'])

          if 'keep_ratio' in solr_data:
              solr_data['keep_ratio'] = float(solr_data['keep_ratio'])

          if 'skip_pages' in solr_data:
              solr_data['skip_pages'] = int(solr_data['skip_pages'])
              if (solr_data['skip_pages'] >= solr_data['max_records'] / solr_data['batch_size']):
                  raise ValueError(f"Implausible skip_pages {solr_data['skip_pages']}")


          return cls(**solr_data)


class SolrRetriever(BaseRetriever):
    solr_url : str = ''
    client: Solr = None
    solr_config : SolrConfig = SolrConfig()
    k: int = 10
    _lok_remover : Optional[Any] = PrivateAttr(default=None)
    _custom_field_remove : Optional[Any] = PrivateAttr(default=None)

    def __init__(self, config_file : str = 'rag_config.ini'):
       super().__init__()
       self.solr_config = SolrConfig.load_config(config_file)
       self.solr_url = f"http://{self.solr_config.host}:{self.solr_config.port}/solr/{self.solr_config.collection}"
       self.k = self.solr_config.batch_size
       self._lok_remover = jq.compile('.fields |= map(with_entries(select(.key | test("LOK") | not)))')
       self._custom_field_remove = jq.compile('.fields |= map(with_entries(select(.key | test("^(S|O)") | not)))')


    def _get_relevant_documents(self, query: str) -> List[Document]:
        if not self.client:
            self.client = Solr(self.solr_url)

        results = self.client.search(query, fl='*', rows=self.k)
        docs = []
        for doc in results.docs:
            content = doc.get('fullrecord', '') or ''
            docs.append(Document(
                page_content=str(content),
                metadata={
                    **{k: v for k, v in doc.items() if k in ['id', 'author', 'title', 'year']}
                }
            ))
        return docs

    def _remove_LOK_and_synonyms(self, record):
         stripped = self._lok_remover.input_value(json.loads(record)).text()
         return self._custom_field_remove.input_value(json.loads(stripped)).text()


    def _get_plain_relevant_documents(self, query: str):
        if not self.client:
            self.client = Solr(self.solr_url)

        results = self.client.search(query, fl='*', rows=self.k)
        docs = []
        for doc in results.docs:
            record = doc.get('fullrecord', '') or ''
            docs.append(Document(page_content=self._remove_LOK_and_synonyms(record)))

        return docs


class SolrBatchRetriever(SolrRetriever):
    _next_cursor : str = PrivateAttr(default='*')
    _query : str = PrivateAttr(default='*:*')
    retrieved_pages : int = 0
    retrieved_records : int = 0

    def __init__(self, query : str, config_file : str = 'rag_config.ini') :
       super().__init__(config_file)
       self._query = query

    def _get_page(self, query):
       params = {
          'q' :  query,
          'rows' : self.k,
          'sort' : 'id desc',
          'cursorMark' : self._next_cursor,
          'fl' : '*'
       }

       results = self.client.search(**params)
       if results.nextCursorMark == self._next_cursor:
           return []
       else:
           self._next_cursor = results.nextCursorMark

       self.retrieved_pages += 1
       return results


    def _get_relevant_documents(self, query: str) -> List[Document]:
       if not self.client:
           self.client = Solr(self.solr_url)

       if self.retrieved_records > self.solr_config.max_records:
           return []

       results = self._get_page(query)
       while self.solr_config.skip_pages != 0 and self.solr_config.skip_pages >= self.retrieved_pages:
          print(f"SKIPPING PAGE {self.retrieved_pages}")
          results = self._get_page(query)

       docs = []
       for doc in results.docs:
           if random.random() > self.solr_config.keep_ratio:
               continue
           content = doc.get('fullrecord', '') or ''
           content = self._remove_LOK_and_synonyms(content)
           docs.append(Document(
               page_content=content,
               metadata={
                   **{k: v for k, v in doc.items() if k in ['id', 'author', 'title', 'year']}
               }
           ))
           self.retrieved_records += 1

       #self.retrieved_records += len(results.docs)
       return docs


    def get_next_batch(self):
        return self._get_relevant_documents(self._query)


if __name__ == "__main__":
#  solr_retriever = SolrRetriever()
#  docs = solr_retriever._get_relevant_documents("*:*")
#  print(docs)

    solr_retriever = SolrBatchRetriever('-id:L*')
    while True:
       docs = solr_retriever.get_next_batch()
       if not docs:
           break
       print(docs)

