#!/bin/bash
set -o errexit -o nounset


forbidden_hosts=("ptah" "sobek" "nu" "ub16" "ub15" "ub27" "ub28")
short_host=$(hostname --short)


for forbidden_host in "${forbidden_hosts[@]}"; do
    if [[ $short_host == "$forbidden_host" ]]; then
        echo "You cannot commit files on $short_host"
        exit 1
    fi
done


# python syntax check
pyflakes /usr/local/ub_tools/cronjobs


exit 0
