/** \file   RegessionTest.h
 *  \brief  Regression test related utility functions and classes.
 *  \author Dr. Johannes Ruscheinski (johannes.ruscheinski@uni-tuebingen.de)
 *
 *  \copyright 2016 Universitätsbiblothek Tübingen.  All rights reserved.
 *
 *  This program is free software: you can redistribute it and/or modify
 *  it under the terms of the GNU Affero General Public License as
 *  published by the Free Software Foundation, either version 3 of the
 *  License, or (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Affero General Public License for more details.
 *
 *  You should have received a copy of the GNU Affero General Public License
 *  along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */
#ifndef REGESSION_TEST_H
#define REGESSION_TEST_H


#include <string>


namespace RegressionTest {


/** \brief Abort if the condition has not been met. */
void Assert(const std::string &test_name, const std::string &condition_as_string, const bool condition);

    
/** \brief Compare two strings that should be identical.
 *  \param test_name      The name used in logs.
 *
 *  \note A log entry will be generated by writing to std::clog.
 *  \return True if the strings matched and false, if they did not match.
 */
bool CompareStrings(const std::string &test_name, const std::string &actual_string,
                    const std::string &expected_string);

    
/** \brief Compares two files that should be identical.
 *
 *  \param test_name      The name used in logs.
 *  \param actual_file    The test generated file.
 *  \param expected_file  An external, presumably rep-existing, file.
 *  \param delete_actual  If true, "actual_file" will be deleted after a successful comparison.
 *
 *  \note A log entry will be generated by writing to std::clog.
 *  \return True if the files matched and false, if they did not match.
 */
bool CompareFiles(const std::string &test_name, const std::string &actual_file, const std::string &expected_file,
                  const bool delete_actual);


} // namespace RegressionTest


#endif // ifndef REGESSION_TEST_H
