To: {email}
From: no-reply-ixtheo@uni-tuebingen.de
Subject: Your IxTheo Translations
MIME-Version: 1.0
Content-Type: multipart/mixed;
        boundary="XXXXboundary text"

This is a multipart message in MIME format.

--XXXXboundary text 
Content-Type: text/plain

The following terms have been attributed to you

--XXXXboundary text 
Content-Type: text/plain;
Content-Disposition: attachment;
        filename="test.txt"

{LOOP keyword_translations}
     {keyword_translations}
{ENDLOOP}

{LOOP vufind_translations}
     {vufind_translations}
{ENDLOOP}


--XXXXboundary text--
.
