// Test harness for TimeUtil::AscTimeToStructTm
//
#include <iostream>
#include <cstdlib>
#include "TimeUtil.h"
#include "util.h"


int Main(int argc, char *argv[]) {
    if (argc != 2)
        ::Usage("asctime_datetime");

    struct tm tm;
    if (not TimeUtil::AscTimeToStructTm(argv[1], &tm)) {
        std::cerr << "Input was not generated by asctime(3)!\n";
        return EXIT_FAILURE;
    }

    std::cout << "The parsed input was converted to " << TimeUtil::StructTmToString(tm) << '\n';

    return EXIT_SUCCESS;
}
