#!/bin/bash
set -o errexit

if [[ $TUEFIND_FLAVOUR == "krimdok" ]]; then
    if [ -e /var/spool/cron/root ]; then # CentOS
        root_crontab=/var/spool/cron/root
    elif [ -e /var/spool/cron/crontabs/root ]; then # Ubuntu
        root_crontab=/var/spool/cron/crontabs/root
    else
        exit 0 # There is no crontab for root.
    fi
    sed --in-place --regexp-extended '/^# END VUFIND AUTOGENERATED/i 45 22 * * 4 "$BIN/generate_kalliope_originators.py" > "${LOG_DIR}/generate_kalliope_originators.py" 2>&1' ${root_crontab}
    cp /usr/local/ub_tools/cronjobs/*_kalliope_* /usr/local/bin
    generate_kalliope_originators.py > /usr/local/var/log/tuefind/generate_kalliope_originators.log 2>&1
    sed --in-place --regexp-extended '/^# END VUFIND AUTOGENERATED/i 0 22 * * 4 "$BIN/update_beacon_files.sh" > "$LOG_DIR/update_beacon_files.log" 2>&1' ${root_crontab}
fi
