#!/bin/bash
set -o errexit


if [[ $TUEFIND_FLAVOUR != "krimdok" ]]; then
    exit 0
fi

if [ -e /var/spool/cron/root ]; then # CentOS
    root_crontab=/var/spool/cron/root
else # Ubuntu
    root_crontab=/var/spool/cron/crontabs/root
fi

sed --in-place '/^# END VUFIND AUTOGENERATED/i 0 1 1 * * "$BIN/update_print_issns_titles_online_ppns_and_online_issns_list.sh"' \
    $root_crontab
