#!/bin/bash
set -o errexit

if [ -z ${TUEFIND_FLAVOUR} ]; then
    echo "TUEFIND_FLAVOUR unset - Skipping"
    exit 0
fi

root_crontab=/var/spool/cron/crontabs/root
cronjobs_template=/usr/local/ub_tools/cpp/data/installer/${TUEFIND_FLAVOUR}.cronjobs

collect_journal_stats_line=$(grep collect_journal_stats ${cronjobs_template})

if [ ! -f ${root_crontab} ]; then
    echo "${root_crontab} does not seem to exist - Skipping"
    exit 0
fi

if [ ! -r ${root_crontab} ]; then
    echo "${root_crontab} not readable - Aborting"
    exit 1
fi


if [ $(echo ${collect_journal_stats_line} | wc --lines) -ne 1 ]; then
    echo "Invalid number of candidate lines in ${cronjobs_template}"
    exit 1
fi

if  grep collect_journal_stats ${root_crontab}; then
    echo "collect_journal_stats line seems already present - skipping further execution"
    exit 0
fi

ref_time=$(echo ${collect_journal_stats_line} | awk '{print $2*100+$1}')
entry_before=$(cat ${root_crontab} | \
    sed '/^# END VUFIND AUTOGENERATED/,$ d' | \
    grep --invert-match '^#' | \
    egrep '^[[:digit:]]+ [[:digit:]]+' | \
    awk -v ref_time="${ref_time}" '$2*100+$1 < ref_time' | \
    tail --lines 1)
line_of_entry_before=$(fgrep --line-number "${entry_before}" ${root_crontab} | awk -F':' '{print $1}')
sed --in-place "${line_of_entry_before}"'a '"${collect_journal_stats_line}" ${root_crontab}
