#!/bin/bash
set -o errexit


if [[ $(hostname) == "ub15.uni-tuebingen.de" ]]; then
    if [ -e /var/spool/cron/root ]; then # CentOS
        root_crontab=/var/spool/cron/root
    else # Ubuntu
        root_crontab=/var/spool/cron/crontabs/root
    fi

    sed --in-place '/^# END VUFIND AUTOGENERATED/i 0 0 1 * * "$BIN/download_krimdok_core.sh"' $root_crontab
fi
